### ISSUE TITLE
似乎需要安卓12才可以正常安装使用

### ISSUE THREAD

**Issue by amokiel** [MoveCloudROY/BiliMusic#2]
换了一个安卓12的设备，可以正常安装使用。体验很不错，页面挺好看的，就是添加方式有点不太方便，其他都挺好。希望可以支持低一点的设备就更好了，比如安卓10
开发者辛苦了，做这种类型的应用的不多，太难找了，这也是凑巧发现了这个项目，多谢！

**Comment by MoveCloudROY** [comment]
确实有挺多bug的，毕竟是两个星期做的项目作业，正在重构和修bug
